liip_imagine:
    
    filter_sets:
        cache: 

        my_thumb:

            quality: 75

            filters:
                thumbnail: { size: [240, 180], mode: outbound }

        avatar:

            quality: 75

            filters:
                thumbnail: { size: [40, 40], mode: outbound }

        show:

            quality: 75

            filters:
                thumbnail: { size: [600, 400], mode: outbound }

        

